# This will run on Travis' 'new' container-based infrastructure
dist: trusty
sudo: required
language: cpp

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: SuperProjetCPP
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/L0L022/SuperProjetCPP.git

# Install dependencies
addons:
  apt:
    sources:
      - sourceline: 'ppa:boost-latest/ppa'
      - 'ubuntu-toolchain-r-test'
      - 'george-edison55-precise-backports'
    packages:
      - boost1.55
      - cmake
      - cmake-data
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - curl
      - g++-5
      - gcc-5

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

jobs:
  include:
    - stage: build
      script:
        - cmake .
        - make doc
        - cd $TRAVIS_BUILD_DIR
        - chmod +x generateDocumentationAndDeploy.sh
        - ./generateDocumentationAndDeploy.sh

    - stage: build
      env:
        - CTEST_OUTPUT_ON_FAILURE=1
      script:
        - cmake -DCMAKE_BUILD_TYPE=Debug .
        - make check
