# This will run on Travis' 'new' container-based infrastructure
dist: trusty
sudo: false
language: cpp

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: SuperProjetCPP
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/L0L022/SuperProjetCPP.git

# Install dependencies
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

jobs:
  include:
    - stage: build
      script:
        - cmake .
        - make doc
        - cd $TRAVIS_BUILD_DIR
        - chmod +x generateDocumentationAndDeploy.sh
        - ./generateDocumentationAndDeploy.sh

    - stage: build
      env:
        - CTEST_OUTPUT_ON_FAILURE=1
      script:
        - cmake .
        - make check
