# This will run on Travis' 'new' container-based infrastructure
dist: trusty
sudo: false
language: cpp

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: SuperProjetCPP
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/L0L022/SuperProjetCPP.git

# Install dependencies
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - curl

jobs:
  include:
    - stage: build
      script:
        - cmake .
        - make doc
        - cd $TRAVIS_BUILD_DIR
        - chmod +x generateDocumentationAndDeploy.sh
        - ./generateDocumentationAndDeploy.sh

    - stage: build
      env:
        - CTEST_OUTPUT_ON_FAILURE=1
      script:
        - curl -sL -o boost.tar.bz2 "https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2"
        - tar xf boost.tar.bz2
        - cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT="$(realpath boost_1_64_0)" .
        - make check
