# This will run on Travis' 'new' container-based infrastructure
dist: trusty
sudo: required
language: cpp

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: SuperProjetCPP
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/DOXYFILE
    - GH_REPO_REF: github.com/L0L022/SuperProjetCPP.git
    - CTEST_OUTPUT_ON_FAILURE: 1

# Install dependencies
addons:
  apt:
    sources:
      - 'ubuntu-toolchain-r-test'
      - 'george-edison55-precise-backports'
    packages:
      - cmake
      - cmake-data
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - curl
      - g++-5
      - gcc-5

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

cache:
  directories:
  - $HOME/boost-install

script:
  - echo -en 'travis_fold:start:boost\\r'
  - if [ -z "$(ls -A $HOME/boost-install)" ]; then curl -sL -o boost.tar.bz2 "https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2" && tar xf boost.tar.bz2 && cd boost_1_64_0 && ./bootstrap.sh && ./b2 -j2 -d0 --with-test --with-signals --with-locale --with-serialization --prefix="$HOME/boost-install" install && cd .. && rm -rf boost_1_64_0; fi
  - echo -en 'travis_fold:end:boost\\r'
  - echo -en 'travis_fold:start:cmake\\r'
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=$HOME/boost-install .
  - echo -en 'travis_fold:end:cmake\\r'
  - echo -en 'travis_fold:start:test\\r'
  - make -j2 check-core
  - make -j2 check-graphics
  - make -j2 check-widget
  - echo -en 'travis_fold:end:test\\r'
  - echo -en 'travis_fold:start:doc\\r'
  - cd $TRAVIS_BUILD_DIR
  - chmod +x doc/generateDocumentationAndDeploy.sh
  - ./doc/generateDocumentationAndDeploy.sh
  - echo -en 'travis_fold:end:doc\\r'
